### ISSUE TITLE
Steam Link will not wake my Hyper-V virtual machine

### ISSUE THREAD

**Issue by technewsguy** [ejsiron/HyperVive#6]
I've installed HyperVive on my Windows 10 machine and configured a Hyper-V virtual machine on the same machine. I also configured a virtual switch with an External Network set to my Realtek PCIe GbE Family Controller nic and checked the box for Allow management operating system to share this network adapter. 
Steam Link (the hardware device) will not wake a my virtual machine. 
Both devices are hard wired on my network.
I have also tried running Magic Packet Sender WOL v1.2 with my ip address and mac addresses specified. That also does not work. BUT if I check the box for Broadcast, my virtual machine DOES wake up(!)
I feel like I'm close to solving this problem, but just need a tiny bit of guidance. Please and thanks in advance!

**Comment by ejsiron** [comment]
I don't have a Steam Link. Can you provide a link to the exact packet sender software you are using? Google results for "Magic Packet Sender WOL v1.2" are a bit unclear and I want to be sure that I am testing with the same thing that you're using.

**Comment by technewsguy** [comment]
It seems that every time I reach out for help, I eventually find my own solution which was in this case to allow UDP traffic on  port 9 in Windows firewall.
Thank you so much for making this software. To pick up where MS left off and add this feature is so very valuable to me and my daughter who will now benefit by being able to wake her personal VM. You've made a small dream come true for me! Thanks again!

**Comment by ejsiron** [comment]
I'm glad that you got this worked out and that you are happy with the tool!
I'll explore ways to adjust the firewall or at least warn about it so that future users don't get caught as well. Thanks for bringing it to my attention!
