### ISSUE TITLE
Event IDs

### ISSUE THREAD

**Issue by fyopolo** [ejsiron/HyperVive#7]
Hi Eric.
I just tested your app, and regardless the action happening (create/delete) it records the same eventID, which is 4001.
Would it be possible for you to fix that?

![image](https://github.com/ejsiron/HyperVive/assets/50895848/58e36369-50fe-4082-b939-bf099051c139)

![image](https://github.com/ejsiron/HyperVive/assets/50895848/8231ffad-78ba-4ef7-b44e-f101fa302dc1)

**Comment by ejsiron** [comment]
This is more of a feature request than a bug report (from the readme: "4001: A checkpoint-related job succeeded").
That said, this seems like a reasonable request. I will look into what I can do to separate the job activities from the job types.

**Comment by ejsiron** [comment]
Addressed in [v3.5](https://github.com/ejsiron/HyperVive/releases/tag/v3.5)

**Comment by fyopolo** [comment]
i like the update! thank you so much Eric!
